"use client";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, Bell, Camera, ChevronRight, CreditCard, LayoutDashboard, LogOut, PieChart, Plus, Target, Wallet, X, Check, LoaderCircle, CalendarDays } from 'lucide-react';
import { createClient } from '../lib/supabase/client';

type Transaction = { id: string; title: string; category: string; kind: 'income'|'expense'; amount: number; occurred_on: string; };
type Budget = { id: string; category: string; limit_amount: number; color: string; };
type Goal = { id: string; name: string; target_amount: number; target_date: string|null; };
type Contribution = { goal_id: string; amount: number; };
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const dateKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};const monthKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`};
const supabase = (process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ? createClient() : null) as ReturnType<typeof createClient> | null;
export default function HomePage(){
 const [user,setUser]=useState<any>(null),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
 const [transactions,setTransactions]=useState<Transaction[]>([]),[budgets,setBudgets]=useState<Budget[]>([]),[goals,setGoals]=useState<Goal[]>([]),[contributions,setContributions]=useState<Contribution[]>([]);
 const [authMode,setAuthMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 const [modal,setModal]=useState<'transaction'|'budget'|'goal'|'contribution'|null>(null),[title,setTitle]=useState(''),[category,setCategory]=useState('Belanja'),[kind,setKind]=useState<'income'|'expense'>('expense'),[amount,setAmount]=useState(''),[targetDate,setTargetDate]=useState(''),[selectedGoal,setSelectedGoal]=useState('');
 const [receiptMsg,setReceiptMsg]=useState(''),[receiptBusy,setReceiptBusy]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
 const notify=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(''),2600)};
 const load=useCallback(async()=>{if(!supabase)return;setBusy(true);setError('');const period=monthKey();const [t,b,g,c]=await Promise.all([
  supabase.from('transactions').select('id,title,category,kind,amount,occurred_on').order('occurred_on',{ascending:false}).order('created_at',{ascending:false}).limit(300),
  supabase.from('monthly_budgets').select('id,category,limit_amount,color').eq('period_key',period).order('category'),
  supabase.from('savings_goals').select('id,name,target_amount,target_date').order('created_at',{ascending:false}),
  supabase.from('savings_contributions').select('goal_id,amount')]);
  const failure=t.error||b.error||g.error||c.error;if(failure)setError(failure.message);else{setTransactions(t.data||[]);setBudgets(b.data||[]);setGoals(g.data||[]);setContributions(c.data||[])}setBusy(false);
 },[]);
 useEffect(()=>{if(!supabase){setReady(true);return}let alive=true;supabase.auth.getUser().then(({data})=>{if(alive){setUser(data.user);setReady(true)}});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user||null);setReady(true)});return()=>{alive=false;subscription.unsubscribe()}},[]);
 useEffect(()=>{if(user)void load();else{setTransactions([]);setBudgets([]);setGoals([]);setContributions([])}},[user,load]);
 const [yr,mo]=monthKey().split('-');const current=transactions.filter(t=>t.occurred_on?.slice(0,7)===`${yr}-${mo}`);const income=current.filter(t=>t.kind==='income').reduce((s,t)=>s+Number(t.amount),0);const expense=current.filter(t=>t.kind==='expense').reduce((s,t)=>s+Number(t.amount),0);const saved=(id:string)=>contributions.filter(c=>c.goal_id===id).reduce((s,c)=>s+Number(c.amount),0);
 async function auth(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');const result=authMode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setBusy(false);if(result.error)setError(result.error.message);else if(authMode==='signup'&&!result.data.session)notify('Cek email untuk konfirmasi akun.');}
 async function signOut(){if(supabase)await supabase.auth.signOut();}
 async function save(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');let result:any;const n=Number(amount.replace(/\D/g,''));if(!n){setBusy(false);return}
  if(modal==='transaction')result=await supabase.from('transactions').insert({title:title.trim(),category,kind,amount:n,occurred_on:dateKey()});
  if(modal==='budget')result=await supabase.from('monthly_budgets').upsert({period_key:monthKey(),category:title.trim(),limit_amount:n,color:'#78907b'},{onConflict:'user_id,period_key,category'});
  if(modal==='goal')result=await supabase.from('savings_goals').insert({name:title.trim(),target_amount:n,target_date:targetDate||null});
  if(modal==='contribution')result=await supabase.from('savings_contributions').insert({goal_id:selectedGoal,amount:n});
  setBusy(false);if(result?.error){setError(result.error.message);return}setModal(null);setTitle('');setAmount('');setTargetDate('');notify('Berhasil disimpan');await load();
 }
 async function parseReceipt(file:File){if(!supabase)return;setReceiptBusy(true);setReceiptMsg('AI sedang membaca nota.');try{const f=new FormData();f.append('file',file);const response=await fetch('/api/receipt',{method:'POST',body:f});const json=await response.json();if(!response.ok)throw new Error(json.error||'Nota gagal dibaca.');const tx=json.transaction;const {error:e}=await supabase.from('transactions').insert({title:tx.title,category:tx.category||'Lainnya',kind:'expense',amount:Number(tx.amount),occurred_on:dateKey()});if(e)throw e;setReceiptMsg(`Tersimpan: ${tx.title} · ${money(Number(tx.amount))}`);notify('Pengeluaran dari nota dicatat');await load()}catch(e){setReceiptMsg(e instanceof Error?e.message:'Terjadi kesalahan.')}finally{setReceiptBusy(false)}}
 const budgetSpent=(cat:string)=>current.filter(t=>t.kind==='expense'&&t.category===cat).reduce((s,t)=>s+Number(t.amount),0);const totalLimit=budgets.reduce((s,b)=>s+Number(b.limit_amount),0);
 const months=useMemo(()=>Array.from({length:6},(_,i)=>{const d=new Date(Number(yr),Number(mo)-1-i,1);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;return {key,label:new Intl.DateTimeFormat('id-ID',{month:'short'}).format(d),in:transactions.filter(t=>t.occurred_on?.startsWith(key)&&t.kind==='income').reduce((s,t)=>s+Number(t.amount),0),out:transactions.filter(t=>t.occurred_on?.startsWith(key)&&t.kind==='expense').reduce((s,t)=>s+Number(t.amount),0)}}).reverse(),[transactions,yr,mo]);const max=Math.max(1,...months.flatMap(m=>[m.in,m.out]));
 if(ready&&!supabase)return <main className="shell"><section className="auth-card"><div className="brand"><span className="brand-icon"><Wallet size={20}/></span><span>ruma<span className="brand-dot">.</span><small>MONEY, MADE SIMPLE</small></span></div><h1>Hubungkan Supabase</h1><p>Tambahkan NEXT_PUBLIC_SUPABASE_URL dan NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY di environment Vercel, lalu redeploy. Untuk lokal, isi kedua nilai tersebut di .env.local.</p></section></main>;
 if(!ready)return <main className="shell"><div className="auth-card">Memuat akun…</div></main>;
 if(!user)return <main className="shell"><section className="auth-card"><div className="brand"><span className="brand-icon"><Wallet size={20}/></span><span>ruma<span className="brand-dot">.</span><small>MONEY, MADE SIMPLE</small></span></div><h1>{authMode==='login'?'Masuk ke Ruma':'Buat akun Ruma'}</h1><p>Data keuanganmu tersimpan aman di akun pribadi.</p><form onSubmit={auth}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Kata sandi<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required autoComplete={authMode==='login'?'current-password':'new-password'}/></label>{error&&<p className="error-message">{error}</p>}<button className="primary-button" disabled={busy}>{busy?<LoaderCircle className="spin"/>:null}{authMode==='login'?'Masuk':'Daftar'}</button></form><button className="auth-switch" onClick={()=>{setAuthMode(authMode==='login'?'signup':'login');setError('')}}>{authMode==='login'?'Belum punya akun? Daftar':'Sudah punya akun? Masuk'}</button></section></main>;
 return <main className="shell"><aside className="sidebar"><a className="brand" href="#"><span className="brand-icon"><Wallet size={20}/></span><span>ruma<span className="brand-dot">.</span><small>MONEY, MADE SIMPLE</small></span></a><div className="side-label">MENU UTAMA</div><nav><button className="nav-item active"><LayoutDashboard size={18}/><span>Dashboard</span></button><button className="nav-item" onClick={()=>document.getElementById('transactions')?.scrollIntoView({behavior:'smooth'})}><CreditCard size={18}/><span>Transaksi</span><span className="nav-count">{transactions.length}</span></button><button className="nav-item" onClick={()=>setModal('budget')}><PieChart size={18}/><span>Anggaran</span></button><button className="nav-item" onClick={()=>setModal('goal')}><Target size={18}/><span>Pos tabungan</span></button></nav><div className="side-bottom"><div className="profile"><div className="avatar">{(user.email||'R').slice(0,2).toUpperCase()}</div><div><b>{user.email}</b><small>Personal account</small></div><button aria-label="Keluar" onClick={signOut}><LogOut size={18}/></button></div></div></aside>
 <section className="main-area"><header className="topbar"><div className="crumb"><span>Workspace</span><ChevronRight size={14}/><b>Dashboard</b></div><div className="top-actions"><div className="month-select"><CalendarDays size={16}/> {new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date())}</div><button className="icon-button" aria-label="Keluar" onClick={signOut}><LogOut size={18}/></button></div></header><div className="content"><div className="welcome-row"><div><div className="eyebrow">{new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date()).toLocaleUpperCase('id-ID')}</div><h1>Ringkasan keuanganmu</h1><p>Data tersimpan di akun {user.email}.</p></div><button className="primary-button" onClick={()=>setModal('transaction')}><Plus size={17}/> Catat transaksi</button></div>
 {error&&<p className="error-message">{error} {error.includes('relation')||error.includes('schema cache')?'Jalankan SQL dari supabase/migrations di Supabase SQL Editor.':''}</p>}
 <div className="stat-grid"><article className="stat-card balance-card"><div className="stat-heading">Saldo bersih bulan ini</div><div className="stat-value">{money(income-expense)}</div><div className="stat-foot">Pemasukan dikurangi pengeluaran bulan ini</div></article><article className="stat-card"><div className="stat-heading">Pemasukan <span className="stat-icon income-icon"><ArrowDownLeft size={17}/></span></div><div className="stat-value">{money(income)}</div><div className="stat-foot">Bulan ini</div></article><article className="stat-card"><div className="stat-heading">Pengeluaran <span className="stat-icon expense-icon"><ArrowUpRight size={17}/></span></div><div className="stat-value">{money(expense)}</div><div className="stat-foot">Bulan ini</div></article></div>
 <div className="dashboard-grid"><section className="panel cashflow-panel"><div className="panel-heading"><div><h2>Arus kas</h2><p>Enam bulan terakhir</p></div></div><div className="chart-legend"><span><i className="legend-in"/> Pemasukan</span><span><i className="legend-out"/> Pengeluaran</span></div><div className="chart"><div className="y-labels"><span>{money(max)}</span><span>{money(max/2)}</span><span>Rp 0</span></div><div className="plot"><div className="gridline g1"/><div className="gridline g2"/><div className="gridline g4"/><svg viewBox="0 0 700 205" preserveAspectRatio="none" aria-label="Grafik arus kas">{(['in','out'] as const).map(k=><polyline key={k} points={months.map((m,i)=>`${i*140},${185-(m[k]/max)*155}`).join(' ')} fill="none" stroke={k==='in'?'#758d79':'#e6ad70'} strokeWidth="3"/>)}</svg><div className="x-labels">{months.map(m=><span key={m.key}>{m.label}</span>)}</div></div></div></section>
 <section className="panel budget-panel"><div className="panel-heading"><div><h2>Anggaran bulan ini</h2><p>Pengeluaran berdasarkan kategori</p></div><button className="text-link" onClick={()=>setModal('budget')}>Tambah <Plus size={14}/></button></div><div className="budget-total"><div><small>Total terpakai</small><b>{money(budgets.reduce((s,b)=>s+budgetSpent(b.category),0))} <span>/ {money(totalLimit)}</span></b></div><div className="budget-ring" style={{background:`conic-gradient(#758c78 0 ${Math.min(100,totalLimit?Math.round(budgets.reduce((s,b)=>s+budgetSpent(b.category),0)/totalLimit*100):0)}%, #edf1eb ${Math.min(100,totalLimit?Math.round(budgets.reduce((s,b)=>s+budgetSpent(b.category),0)/totalLimit*100):0)}% 100%)`}}><div><b>{totalLimit?Math.round(budgets.reduce((s,b)=>s+budgetSpent(b.category),0)/totalLimit*100):0}%</b><small>terpakai</small></div></div></div><div className="budget-list">{budgets.length?budgets.map(b=><div className="budget-row" key={b.id}><div className="budget-label"><span>{b.category}</span><b>{money(budgetSpent(b.category))} / {money(b.limit_amount)}</b></div><div className="progress"><i style={{width:`${Math.min(100,budgetSpent(b.category)/Number(b.limit_amount)*100)}%`,background:b.color}}/></div></div>):<p>Belum ada alokasi. Tambahkan batas bulanan per kategori.</p>}</div></section>
 <section className="panel transactions-panel" id="transactions"><div className="panel-heading"><div><h2>Transaksi terbaru</h2><p>{transactions.length} transaksi tersimpan</p></div><button className="text-link" onClick={()=>setModal('transaction')}>Tambah <Plus size={14}/></button></div><div className="transaction-list">{transactions.slice(0,8).map(t=><div className="transaction-row" key={t.id}><span className="transaction-icon">•</span><div className="transaction-name"><b>{t.title}</b><small>{t.category} · {new Date(`${t.occurred_on}T00:00:00`).toLocaleDateString('id-ID')}</small></div><b className={t.kind==='income'?'amount-in':'amount-out'}>{t.kind==='income'?'+':'−'}{money(Number(t.amount))}</b></div>)}{!transactions.length&&<p>Belum ada transaksi. Mulai dengan mencatat pemasukan atau pengeluaran.</p>}</div></section>
 <section className="panel goals-panel"><div className="panel-heading"><div><h2>Pos tabungan</h2><p>Setoran tercatat di akunmu</p></div><button className="round-plus" onClick={()=>setModal('goal')}><Plus size={17}/></button></div><div className="goal-list">{goals.map(g=><div className="goal-row" key={g.id}><div className="goal-top"><div className="goal-name"><span>•</span><div><b>{g.name}</b><small>{g.target_date?`Target ${new Date(`${g.target_date}T00:00:00`).toLocaleDateString('id-ID')}`:'Tanpa tanggal target'}</small></div></div><b>{Math.min(100,Math.round(saved(g.id)/Number(g.target_amount)*100))}%</b></div><div className="progress goal-progress"><i style={{width:`${Math.min(100,saved(g.id)/Number(g.target_amount)*100)}%`}}/></div><div className="goal-foot"><span>{money(saved(g.id))} <small>terkumpul</small></span><span>{money(Number(g.target_amount))}</span></div></div>)}{!goals.length&&<p>Belum ada tujuan tabungan.</p>}</div><button className="goal-action" onClick={()=>{if(!goals.length){setModal('goal');return}setSelectedGoal(goals[0].id);setModal('contribution')}}>Tambah setoran tabungan <ChevronRight size={15}/></button></section></div>
 <section className="receipt-banner"><div className="receipt-art"><div className="art-circle"><Camera size={25}/></div></div><div className="receipt-copy"><span className="ai-pill">DIDUKUNG AI</span><h3>Foto atau unggah nota</h3><p>AI membaca nominal dan kategori, lalu simpan ke transaksi akunmu.</p></div><button disabled={receiptBusy} onClick={()=>fileRef.current?.click()}>{receiptBusy?<LoaderCircle className="spin"/>:<Camera size={17}/>} Scan nota</button><input ref={fileRef} type="file" accept="image/*" capture="environment" hidden onChange={e=>{const f=e.currentTarget.files?.[0];if(f)void parseReceipt(f);e.currentTarget.value=''}}/></section>{receiptMsg&&<div className="receipt-status">{receiptMsg}</div>}
 <footer>2026 Ruma Finance <span>Data milik akunmu.</span></footer>{busy&&<div className="loading-note">Menyimpan / memuat…</div>}</div></section>
 {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><section className="modal"><div className="modal-title"><div><span className="modal-icon">{modal==='transaction'?<Wallet size={18}/>:modal==='budget'?<PieChart size={18}/>:<Target size={18}/>}</span><div><h2>{modal==='transaction'?'Catat transaksi':modal==='budget'?'Anggaran bulanan':modal==='goal'?'Pos tabungan':'Setoran tabungan'}</h2><p>Data akan disimpan di akunmu.</p></div></div><button onClick={()=>setModal(null)}><X size={19}/></button></div><form onSubmit={save}>{modal==='contribution'?<label>Pos tabungan<select value={selectedGoal} onChange={e=>setSelectedGoal(e.target.value)} required>{goals.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>:<label>{modal==='transaction'?'Nama transaksi':modal==='budget'?'Kategori anggaran':'Nama tujuan'}<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} required placeholder={modal==='transaction'?'Contoh: Makan siang':modal==='budget'?'Contoh: Transportasi':'Contoh: Dana darurat'}/></label>}{modal==='transaction'&&<><label>Jenis transaksi<select value={kind} onChange={e=>setKind(e.target.value as any)}><option value="expense">Pengeluaran</option><option value="income">Pemasukan</option></select></label><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}>{['Makanan & minuman','Transportasi','Belanja','Tagihan','Kesehatan','Pendidikan','Hiburan','Lainnya'].map(c=><option key={c}>{c}</option>)}</select></label></>}{modal==='goal'&&<label>Tanggal target (opsional)<input type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)}/></label>}<label>{modal==='transaction'?'Jumlah (Rp)':modal==='budget'?'Batas per bulan (Rp)':modal==='goal'?'Target tabungan (Rp)':'Jumlah setoran (Rp)'}<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="500000" required/></label>{error&&<p className="error-message">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setModal(null)}>Batal</button><button className="primary-button" disabled={busy}><Check size={16}/> Simpan</button></div></form></section></div>}{toast&&<div className="toast"><Check size={16}/>{toast}</div>}</main>;
}



